services:
  - type: web
    name: fmp-chat-proxy
    env: docker
    plan: free
    envVars:
      - key: FMP_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ACTION_KEY
        sync: false
      - key: OPENAI_MODEL
        sync: false
      - key: CORS_ORIGINS
        sync: false
